ТЗ 14
flykeeperB/java-shareit pull request #2
Opened 2023-07-23 17:07 UTC by flykeeperB

реализовать механизм бронирования, комментирования

2023-07-24 14:14 UTC, alexache requested changes

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/BasicValidator.java
> +    public void validateUserId(Optional<Long> userId) {
1. Сначала должны идти публичные методы, а уже потом протектед-приватные
2. Лучше пользоваться полноценно интерфейсом Optional - Optional.orElseThrow(() -> new ValidationException()
3. Как-то слишком много методов с малым функционалом, не обязательно обобщать все, и в дублировании текстов исключений нет ничего плохого

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/Service.java
> +    String getName();
Эти хаки для обобщенный абстрактных сервисов, стораджей, выглядят странно с точки зрения интерфейса

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public void forApprove(Booking source, Optional<Long> userId, Boolean isApproved) {
Пропущены @Override?

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/impl/BookingControllerImpl.java
> +        super(service, mapper);
Как-то все это усложненно с дублированием полей

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/impl/BookingControllerImpl.java
> +        logInfo("обработка запроса на получение сведений о бронированиях для отдельного пользователя");
чем плох обычный log.info?

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/impl/BookingServiceImpl.java
> +            result.put(TypesOfBookingConnectionToItem.LAST, bookings.get(0));
Если всегда нужна только 1 запись из списка, то можно добавить findFirst1* в имя метода

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/impl/BookingServiceImpl.java
> +    public List<Booking> retrieveComplitedForBooker(Optional<Long> userId, State state) {
Не очень понятный метод

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/mapping/BookingMapper.java
> +    private final UserMapper userMapper;
Маппер должен быть очень простым без использования каких-либо внешних сервисов. Использование других мапперов - ок, но тоже не идеально

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode(callSuper = true)
Эта аннотация несовместима с JPA поскольку сгенерированные методы не учитывают специфику JPA моделей

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Это относится и к @Data аннотации, которая тоже включает в себя EqualsAndHashcode

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        result.forEach(this::setBookingsForItem);
Это уже запрос к базе в цикле, что недопустимо, Запрос должен быть 1 по списку вещей

2023-07-24 14:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode(callSuper = true)
Повторный коммент про аннотации и модель

2023-07-24 14:14 UTC, alexache commented on src/main/resources/application.properties
> +spring.main.allow-circular-references=true
Это очень плохой знак, что требуется такое свойство

2023-08-11 22:38 UTC, flykeeperB commented on src/main/resources/application.properties
> +spring.main.allow-circular-references=true
Свойство исключено за ненадобностью.

2023-08-11 22:38 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@EqualsAndHashCode(callSuper = true)
Аннотации lombok, вмешивающиеся в toString, hashCode, equals исключены.

2023-08-11 22:39 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Аннотации lombok, вмешивающиеся в toString, hashCode, equals исключены.

2023-08-11 22:40 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        result.forEach(this::setBookingsForItem);
Метод переработан, добавлено обращение к методу, получающему перечень нужных бронирований по списку идентификаторов одним запросом.

2023-08-11 22:40 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode(callSuper = true)
Аннотации lombok, вмешивающиеся в toString, hashCode, equals исключены.

2023-08-11 22:41 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/booking/impl/BookingControllerImpl.java
> +        logInfo("обработка запроса на получение сведений о бронированиях для отдельного пользователя");
возвращено использование стандартного вызова log.info.
В предыдущей версии кода метод logInfo добавлял некоторые дополнительные сведения к сообщению об ошибке.

2023-08-11 22:43 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/booking/impl/BookingControllerImpl.java
> +        super(service, mapper);
Код приложения значительно переработан, в том числе исключены усложняющие чтение кода абстракции.

2023-08-11 22:45 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public void forApprove(Booking source, Optional<Long> userId, Boolean isApproved) {
Код приложения значительно переработан: взамен сложного единого класса-валидатора, содержащего множество методов валидации, добавлены атомарные валидаторы, специализирующие на минимальных проверках, что упрощает их изменение, добавление новых проверок.
Замечание утратило актуальность.

2023-08-11 22:46 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/Service.java
> +    String getName();
Код приложения значительно переработан, в том числе исключены усложняющие чтение кода абстракции.

2023-08-11 22:48 UTC, flykeeperB commented on src/main/java/ru/practicum/shareit/BasicValidator.java
> +    public void validateUserId(Optional<Long> userId) {
Код переработан. Методы классов изложены по указанному в замечании порядку, в случаях использования Optional<T> исключения при проверках на null выбрасываются указанным в замечании способом, концепция валидации переработана: взамен сложного единого класса-валидатора, содержащего множество методов валидации, добавлены атомарные валидаторы, специализирующие на минимальных проверках, что упрощает их изменение, добавление новых проверок.

2023-08-12 10:12 UTC, alexache approved these changes

2023-08-12 10:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = this.retrieve(approveBookingRequest.getTargetBookingId());
(очень минорный) А для чего this?

2023-08-12 10:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        availabilityForBookingValidator.validate(request);
Внутри валидатора запрос к базе для получения вещи, ниже тоже есть запрос к базе для того же, уже немного не оптимально, такого следует избегать

2023-08-12 10:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        sharerUserValidator.validate(request);
Так же и здесь с получением пользователя

2023-08-13 18:20 UTC, merged